### ISSUE TITLE
company activity property

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Business-Vocabulary#10]
I probably would use legalEntityActivity as name of this property, if we use the term LegalEntity. For instance, a no-profit organisation (that is not a public organisation) can it be modelled using the LegalEntity class? If so probably I would not say that a no-profit organisation is a company. That's why I am suggesting to use the name of the main class in the name of the property.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, participants agreed to rename the property to "legalEntityActivity".

**Comment by EmidioStani** [comment]
Resolved, see #11
