### ISSUE TITLE
company type property

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Business-Vocabulary#11]
is the company type property the legal form of the legal entity? In the eprocurement ontology we call it legalFormType  and it seems to me clearer

**Comment by aidig** [comment]
Might [rov:orgType ](https://www.w3.org/TR/vocab-regorg/#ref_rov_orgType)from the Registered Organization Vocabulary be useful here?


> 
> <h3 id="ref_rov_orgType" style="text-align: left; color: rgb(0, 90, 156); background: white; font: 19.2px sans-serif; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Organization Type</h3>
> Property | Domain | Range
> -- | -- | --
> rov:orgType _(rdfs:subPropertyOf org:classification)_ | org:Organization | skos:Concept
> 
> <p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This property records the type of company. Familiar types are SA, PLC, LLC, GmbH etc. At the time of publication, there is no agreed set of company types that crosses borders. The term 'SA' is used in Poland and France for example although they mean slightly different things. The UK's LLP and Greece's EPE provide further example of close, but not exact, matches.</p><p style="color: rgb(0, 0, 0); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">That said, each jurisdiction will have a limited set of recognized company types and these should be expressed in a consistent manner in a SKOS Concept Scheme.</p>
> 
> 

Also, regarding differing type sets for different countries see: https://en.wikipedia.org/wiki/List_of_legal_entity_types_by_country
https://iate.europa.eu/entry/slideshow/1621424608507/3564078/en-en-la-mul

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, an agreement was reached to name the property "legalFormType".

**Comment by EmidioStani** [comment]
Resolved, eventual discussion on the legal entity definition can continue on GitHub
