### ISSUE TITLE
constraints in the core vocabularies

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Business-Vocabulary#12]
if it is core vocabulary,  constraints should not be indicated, right? At least in the other vocabularies there are no constraints at all in the object properties while in this vocabulary they are indicated. I would be uniform with respect to the others.

**Comment by aidig** [comment]
Agree that multiplicity/cardinality constraints should not be present in core vocabularies

**Comment by EmidioStani** [comment]
It can be closed, the consolidated diagram should not have any cardinalities: https://github.com/SEMICeu/Core-Business-Vocabulary/tree/master/releases/2.00
