### ISSUE TITLE
Terminology and definitions in the core vocabularies 

### ISSUE THREAD

**Issue by aidig** [SEMICeu/Core-Business-Vocabulary#16]
see https://github.com/SEMICeu/CPOV/issues/12

**Comment by EmidioStani** [comment]
we have proposed a [set of rules](https://github.com/SEMICeu/CPOV/blob/master/generic/Principles for creating good definitions_v1.00.pdf) for defining concepts. We have also detailed an approach to apply these rules as strictly as possible while ensuring that we don't break semantic interoperability of existing definitions. Comments on these rules are welcome!

**Comment by EmidioStani** [comment]
updated definitions has been published on: https://github.com/SEMICeu/Core-Business-Vocabulary/blob/master/releases/2.00/Changelog_definitions.md
