### ISSUE TITLE
Multiple relationships

### ISSUE THREAD

**Issue by RobWalker867** [SEMICeu/Core-Business-Vocabulary#17]
The core business model appears over-simplified. It only covers registration. Many businesses trade under more than one name, which can be different from the legal name. It is important for local authorities to record these. They also need to know the range of addresses which these businesses operate from. For example, a restaurant business may be registered at an accountant’s office address, but operate at several premises.

**Comment by makxdekkers** [comment]
The Core Business vocabulary includes a property (optional and repeatable) for alternative names. It may indeed be useful to add a link to other addresses to the Core Vocabulary.

**Comment by RobWalker867** [comment]
Individual alternative names might need to be associated with particular addresses. The model currently only allows a single address for a legal entity.

**Comment by makxdekkers** [comment]
@RobWalker867 In the use case that the Core Business vocabulary supports, there is indeed an expectation that a legal entity has a single registered address. I would think that this is always the case, isn't it?. Additional use cases like the one you mention here, to provide information under which different names the legal entity might operate at different addresses, was not in the original use case of the vocabulary and therefore is not supported.

**Comment by GeertThijs** [comment]
See issue #30 in this respect. Right now, it is not really clear that LegalEntity by being a subclass of FormalOrganization is actually a subclass of Organization from the [Organization Ontology](https://www.w3.org/TR/vocab-org/#org:FormalOrganization). Take a look at all the attributes from Organization which are implicitliy are inherited by LegalEntity. One of those being a link with the Site or Sites of an Organization; It is actually those Sites that carry the address (addresses) of an organization. In [our rendering](https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis) of Organization and RegisteredOrganization for our semantic project in Flanders called [OSLO ](https://www.vlaanderen.be/digitaal-vlaanderen/onze-oplossingen/oslo)(Open Standard for Linked Organizations), we added an attribute Organization.contactinfo, which also includes an adress. And between the links with the Sites of an Organization you will find one called "hasRegisteredSite" from which a registered Address can be obtained.

**Comment by EmielPwC** [comment]
During the [webinar](https://joinup.ec.europa.eu/sites/default/files/inline-files/20230221%20Webinar%20Core%20Vocs_1.pdf) of 21/02/2023 it has been approved to:


Reuse the relations from Organization ontology ( hasSubOrganization, subOrganizationOf)

**Comment by EmidioStani** [comment]
The release [2.1.0](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.1.0/) addressed the points of the webinar, this issue can be closed.
