### ISSUE TITLE
LegalEntity class, backward compatibility and a new class

### ISSUE THREAD

**Issue by pebran** [SEMICeu/Core-Business-Vocabulary#21]
For reasons I have found no documentation for the class LegalEntity has changed – in the proposal for version 2 – in a way that breaks backward compatibility. 
In version 2.0 LegalEntity is described as being a subclass of org:FormalOrganization.
In version 1.0 LegalEntity was declared as being a subclass of foaf:Agent. This is documented in the specification [1], in the UML-file [2]. 

That the class foaf:Agent was the intended superclass for LegalEntity is further stressed by the discussion in the two issues ‘ISACV-125 Business – how is a Business different from an Organisation?’ and ‘ISACV-129 Business – How is a Business different from a (natural) Person?’ raised within the working group [3].

Only in the RDF-file [4] is org:FormalOrganization mentioned as the superclass for LegalEntity. 
I would argue that foaf:Agent has been the intended superclass all the time and that the RDF-file is containing a mistake. 

Changing the vocabulary now to let LegalEntity be a subclass of org:FormalOrganization will not only go against the intention with the class as it has been described in both the documentation and in the working group notes. It will also break backward compatibility. LegalEntity as is was defined in version 1.0 includes persons hat acts as LegalEntity, i.e.  by being the sole owner and employee of a ‘SinglePersonBusiness’. 

We would therefore ask that you keep letting LegalEntity be a direct subclass of foaf:Agent.
However, we do agree that there is a need for a construction that provides us with a type of legal entity that is a formal organization. We therefore suggest that a new class LegalEntityOrganisation is defined as being a subclass of both LegalEntity and of FormalOrganization. Other names for the class are off course possible.

 
![billede](https://user-images.githubusercontent.com/391743/143297351-7eee0d08-784e-45f5-a674-049bab5a2e0c.png)

Regards,
Peter Bruhn Andersen
Danish Agency for Digitisation

[1]   https://github.com/SEMICeu/Core-Business-Vocabulary/blob/master/releases/1.00/Core_Vocabularies-Business_Location_Person-Specification-v1.00.docx 
[2]   https://github.com/SEMICeu/Core-Business-Vocabulary/blob/master/releases/1.00/Core_Vocabularies-Business_Location_Person_v1.00_Conceptual_Model.EAP 
[3]   https://github.com/SEMICeu/Core-Business-Vocabulary/blob/master/releases/1.00/Core_Vocabularies-Business_Issues_Raised_within_Working_Group-v1.00.zip 
[4]   https://github.com/SEMICeu/Core-Business-Vocabulary/blob/master/releases/1.00/Core_Vocabularies-Business_Location_Person_v1.00_RDF_Schema.zip

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021 it was explained that documentation was used to simplify the indirect relation between foaf:Agent and Legal Entity and then Legal Entity was always a subclass org:FormalOrganization.
