### ISSUE TITLE
Relationship with W3C Registered Organization Vocabulary?

### ISSUE THREAD

**Issue by sskagemo** [SEMICeu/Core-Business-Vocabulary#23]
On the Core Business Vocabulary page on JoinUp, it is stated that this vocabulary is publised as W3C Registered Organization Vocabulary:

"Since 8 January 2013, an RDF syntax of the Core Business Vocabulary has been formally published on the W3C standards track. It has been revised and renamed into [Registered Organization Vocabulary](http://www.w3.org/TR/vocab-regorg/) (RegOrg). [>> Read more](https://joinup.ec.europa.eu/news/publication-core-busin)"

Source: https://joinup.ec.europa.eu/collection/registered-organization-vocabulary/solution/registered-organization-vocabulary/release/100

Unfortunatly the link to "read more" is broken.

I would assume the vocabularies were co-ordinated, but for instance RegOrg uses "RegisteredOrganization", while Core Business Vocabulary uses Legal Entity:

![image](https://user-images.githubusercontent.com/5012227/153413620-dbb45a7b-b961-4b75-9ea6-3c5fe396b471.png)

Core Business Vocabulary v.1:
![image](https://user-images.githubusercontent.com/5012227/153413727-0ef4cf53-4e0c-4602-a638-2153e24a0ec0.png)

Is this intentional? Is the Registered Organization Vocabulary still the authoritative RDF-version of the vocabulary?

**Comment by EmidioStani** [comment]
Dear @sskagemo, I believe you are looking at an old version of the Core Vocabularies, the current can be found here:

https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/

**Comment by sskagemo** [comment]
Thank you!
