### ISSUE TITLE
Relation with REGORG

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/Core-Business-Vocabulary#25]
What is the relation of this VOC with the [REGORG VOC](https://www.w3.org/TR/vocab-regorg/)? I am under the impression that they cover broadly the same domain. REGORG was a continuation of the Core Business VOC v1.0, so why not start from REGORG for the Core Business VOC v2.0 so as not to end up with different uri's for what is actually the same concept. Eg LegalEntity was rebranded to RegisteredOrganisation by REGORG, following the reasoning that an Organization becomes a LegalEntity when it is officially registered. So why has the Core Business VOC 2.0 redefined concepts that already in REGORG?

**Comment by GeertThijs** [comment]
SeeAlso issue #27

**Comment by EmidioStani** [comment]
The decision, in agreement with W3C, is to redirect the legal namespace:

http://www.w3.org/ns/legal

to Core Business

While the regorg stays on W3C: https://www.w3.org/TR/vocab-regorg/

Keep in mind that reg org is a Working Group Note and not a W3C recommendation like Organization Ontology: https://www.w3.org/TR/vocab-org/ and it is not currently maintained.
