### ISSUE TITLE
Core Business Vocabulary identical to RegisteredOrganisations Vocabulary.

### ISSUE THREAD

**Issue by GeertThijs** [SEMICeu/Core-Business-Vocabulary#27]
The [Core Business Vocabulary](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/) (CBV) is almost identical to the already existing [RegisteredOrganisations Vocabulary](https://www.w3.org/TR/vocab-org/) (REGORG). The model is nearly exactly the same, specializing FormalOrganization from the [Organization Ontology](https://www.w3.org/TR/vocab-org/). Definitions are almost identical, some text is literally copied from REGORG. Attributes are more ore less the same, they were just given different names. Is there any good reason for this? We use REGORG since 2017 in Flanders as part of our semantic interoperability project known as [OSLO ](https://www.vlaanderen.be/digitaal-vlaanderen/onze-oplossingen/oslo)(Open Standards for Linking Organizations). One of our most important rules is to adhere to and reuse as many existing standards/ontologies as possible so as not to hamper interoperability by creating different identifiers for identical concepts. Solution here would be to include equivalence statements in the CBV RDF spec, but better would be to actually reuse the REGORG uri's (and labels).

**Comment by GeertThijs** [comment]
Just to illustrate that both ontologies are identical, see the following UML class diagrams recreated from both ontologies put side-by-side:
![image](https://user-images.githubusercontent.com/22620291/189874781-9e48a087-59d1-4dfa-9d19-eb7b29cd05c4.png)
Only differences are:

- different class name
- different attribute names
- REGORG.RegisteredOrganization points to the address of the Organization in an indirect way

**Comment by EmidioStani** [comment]
EGORG Voc is not anymore maintained, the continuation is Core Business Vocabulary.

**Comment by GeertThijs** [comment]
> EGORG Voc is not anymore maintained, the continuation is Core Business Vocabulary.

I understand. However, I rather experience it as a continuation of the Core Business Vocabulary 1.0 as certain improvements made by RegOrg to it are discarded. see issues #25, #26, #28, #29 and #30. Meanwhile I assume RegOrg remains online so we can continue to use it?

**Comment by EmidioStani** [comment]
Hello @GeertThijs ,

Redirection from RegOrg to Core Business will be put in place at a certain point in time, until then it is definitely possible to use it.

**Comment by GeertThijs** [comment]
> Hello @GeertThijs ,
> 
> Redirection from RegOrg to Core Business will be put in place at a certain point in time, until then it is definitely possible to use it.

Before any redirection is put in effect, I would like you to consider the above mentioned issues. In short these are: LegalEntity is to broad a name for a RegisteredOrganization, as a result the definition of it does not correspond with a Business or RegisteredOrganization, the namespace ns/legal is not a good choice, certain attributes should be inherited from org:Organization and for localisation of the Business a link with its Site is a better solution.

**Comment by EmidioStani** [comment]
The decision, in agreement with W3C, is to redirect the legal namespace:

http://www.w3.org/ns/legal

to Core Business

While the regorg stays on W3C: https://www.w3.org/TR/vocab-regorg/

Keep in mind that reg org is a Working Group Note and not a W3C recommendation like Organization Ontology: https://www.w3.org/TR/vocab-org/ and it is not currently maintained.
