### ISSUE TITLE
legal:legalIdentifier definition missing in the RDFS vocabulary

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/Core-Business-Vocabulary#35]
`legal:legalIdentifier` definition is missing in the [RDFS vocabulary](https://github.com/SEMICeu/Core-Business-Vocabulary/blob/master/releases/2.00/voc/core-business-ap.ttl).
![image](https://user-images.githubusercontent.com/718827/207002881-2ecc62d8-a567-41d8-bdb9-695e640aa685.png)

**Comment by EmielPwC** [comment]
Thank you @jakubklimek  it will be fixed in the next release.

**Comment by EmidioStani** [comment]
The release [2.1.0](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.1.0/) added legalidentifier property
