### ISSUE TITLE
Relation with schema.org Organization

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/Core-Business-Vocabulary#38]
What is the relation of [`legal:LegalEntity`](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/#Legal%20Entity) and [`schema:Organization`](https://schema.org/Organization)?

We might either
1. add a mapping, or
2. not want to add that mapping due to various reasons, not supporting the mixture of EU vocabularies and schema.org properties, but then we should be explicit about it. Right now it seems like someone forgot schema.org exists.

**Comment by EmidioStani** [comment]
Hello @jakubklimek ,

so far the intention is to provide mapping, I started with DCAT-AP for the time being, which put some clarity as well as in DCAT.

Independently for the mapping itself, a publication method has to be foreseen.

**Comment by GeertThijs** [comment]
A legal:LegalEntity/regorg:RegisteredOrgan,zation is a subclass of schema:Organization (and org:Organization). Not every Organization (in essence an association of Persons) is officially registered.

**Comment by EmidioStani** [comment]
Semantic mappings with Schema.org have been published.

In the case of Legal Entity, the mapping is with schema:Organization as subclassOf, see: https://github.com/SEMICeu/Semantic-Mappings/tree/main/Core%20Business/Schema.org
