### ISSUE TITLE
Alignment with HVD

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/Core-Business-Vocabulary#39]
Within the HVD: 

https://ec.europa.eu/info/law/better-regulation/have-your-say/initiatives/12111-Open-data-availability-of-public-datasets_en

in the Annex (Ares) - Section 5.1 - page 32

There is a mention of different properties for a Company, 2 of them are not present in Core Business (while the others can be mapped to Core Business:

1) registration date
2) Accounting document

This issue is to trigger discussion on this alignment.

**Comment by jakubklimek** [comment]
I would also suggest creating a data instance example to show how exactly a company can be described using Core Business Vocabulary in an HVD-compliant way similarly to the [STIRData example](https://stirdata.github.io/data-specification/#czech-company-example)

**Comment by EmielPwC** [comment]
The Commission Implementing Regulation has been published on https://eur-lex.europa.eu/eli/reg_impl/2023/138/oj.
Information on companies can be found in the Annex section 5.1.
No changes from the previous link above in the issue have occured.

**Comment by EmielPwC** [comment]
During the [webinar](https://joinup.ec.europa.eu/sites/default/files/inline-files/20230221%20Webinar%20Core%20Vocs_1.pdf) of 21/02/2023 it has been approved to:

-  add registration date property within the Legal Entity class with the following definition: "The date on which the legal entity has registered in some jurisdiction for regulatory and / or for tax purposes”
- add Accounting Document class  with the following definition: “Financial and non-financial information as
a result of an activity of an organisation.” and usage note corresponding to the legal text.
