### ISSUE TITLE
Cardinality of LegalEntityID 

### ISSUE THREAD

**Issue by SusanneWigard** [SEMICeu/Core-Business-Vocabulary#4]
In version 1.91 (the latest published version on Joinup of the XML representaiton CoreVocabularies-AggregateComponents-1.1.xsd), LegalEntityID has cardinalities minOccurs="1" and maxOccurs="1" whereas as LegalEntityLegalID or PersonID (and all other IDS that I checked) have minOccurs="0" and maxOccurs="unbounded". 

In the UML diagram Core_Vocabularies-Business_Location_Person_v1.00_Conceptual_Model.png the cardinality is 0..1.  

Probably  minOccurs="0" and maxOccurs="unbounded" would be correct, which is also more consistent with the general idea that Core Vocabularies don’t restrict cardinalities because this should be done in the domain vocabularies using them. In any case the identifier should not be mandatory.

**Comment by EmidioStani** [comment]
This issue concerns Core Vocabularies 1.0 which is now deprecated and not maintained.

Core Vocabularies do not impose cardinalities and this is reflected the latest release as well.
