### ISSUE TITLE
Alignment with BRIS

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/Core-Business-Vocabulary#40]
Within the BRIS:

https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:02017L1132-20200101&from=EN#tocId40

Article 19

There is a list of properties for which Member States shall provide for interconnections of registers, among them the following is not present in Core Business:

- details of the company website, where such details are recorded in the national register

For this property it is possible to reuse https://semiceu.github.io/CPOV/releases/2.1.0/#Contact%20Point

The following properties:

- Contact Point of Person: the particulars of any persons who either as a body or as members of any such body are currently authorised by the company to represent it in dealing with third parties and in legal proceedings and information as to whether the persons authorised to represent the company may do so alone or are required to act jointly.
- Branches: information on any branches opened by the company in another Member State including the name, registration number, EUID and the Member State where the branch is registered.

are implicit within the core business model as LegalEntity is indirectly subclass of org:Organization thus inheriting relations like hasMember/headOf and hasUnit, see more on https://www.w3.org/TR/vocab-org/#overview-of-ontology

**Comment by EmielPwC** [comment]
During the [webinar](https://joinup.ec.europa.eu/sites/default/files/inline-files/20230221%20Webinar%20Core%20Vocs_1.pdf) of 21/02/2023 it has been approved to:

- Reuse ContactPoint class from CPOV with contactPoint relation
-Reuse the relations from Organization ontology (memberOf, hasMember, headOf, hasSubOrganization, subOrganization)
