### ISSUE TITLE
"identifies" uses wrong IRI scheme in RDFS version of the vocabulary

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/Core-Business-Vocabulary#41]
In https://github.com/SEMICeu/Core-Business-Vocabulary/blob/d7ed70b61a6c67d69d82314106d668d4aa5e6207/releases/2.00/voc/core-business-ap.ttl#L12, `identifies` is defined like so:
```turtle
<https://data.europa.eu/m8g/identifies> a owl:ObjectProperty;
  rdfs:domain <http://www.w3.org/ns/adms#Identifier>;
  rdfs:isDefinedBy <https://data.europa.eu/m8g>;
  rdfs:range <http://www.w3.org/ns/legal#LegalEntity> .
```
However, the prefix `m8g` uses `http` scheme, not `https`. I suggest using the prefix instead of the (wrong) full IRI.

**Comment by EmidioStani** [comment]
Hello @jakubklimek ,

thanks for reporting this inconsistency, it will be fixed in the next release.
