### ISSUE TITLE
Change legal entity activity usage note to require/prefer usage of NACE from EU Vocabularies

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/Core-Business-Vocabulary#42]
[Statistical Classification of Economic Activities in the European Community Rev. 2 (NACE)](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/nace2) was published in the EU Vocabularies. Therefore, this representation should be preferred or even required for [legal entity activity](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/#Legal%20Entity%3Alegal%20entity%20activity).

NACE is indeed mentioned as the preferred codelist to be used, however, it links to the old web view of the codelist. I suggest linking directly to the [EU Vocabularies](https://op.europa.eu/en/web/eu-vocabularies/dataset/-/resource?uri=http://publications.europa.eu/resource/dataset/nace2) page an consider making the use of this codelist mandatory, similarly to DCAT-AP properties such as theme, which also make the usage of the corresponding EU Vocabularies codelist mandatory (and allowing usage of any other code list on top of that).

Related to #39

**Comment by EmidioStani** [comment]
Hello @jakubklimek 

NACE is already considered the "preferred choice" in the usage note of the legal entity activity, however the hyperlink could point to the EU vocabularies, to be fixed in the next release

**Comment by EmidioStani** [comment]
The release [2.1.0](https://semiceu.github.io/Core-Business-Vocabulary/releases/2.1.0/) fixed the hyperlink to the EU vocabulary.
