### ISSUE TITLE
Publishing of the RDF/OWL or JSON-LD version with resolvable URIs and content negotiation on EU server

### ISSUE THREAD

**Issue by jgmikael** [SEMICeu/Core-Business-Vocabulary#43]
### Use case name

Publication with resolvable URIs and content negotiation on server

### Please insert the status of the use case

Idea

### Use case creator

Mikael af Hällström

### Stakeholders

Data producers or publishers who wish to create their own data models by accessing the EU Core Vocabulary classes and properties directly online with the help of their own semantic technology based modeling tools.

### Problem statement

At present the EU Core Vocabularies are published only in a number of downloadable formats for offline use. If specifically the RDF representation or the JSON-LD context versions would be published in the same manner as the UN/CEFACT BSP JSON-LD vocabulary, this would enable the direct online reference and use of all the EU Core Vocabularies in modeling tools that are based on the use of W3C Linked Data. One instance of such a tool is the world leading Interoperability Platform, developed by the Finnish Ministry of Finance and the Digitalization Agency of Finland, but probably other similar solutions do exist in other EU Member States as well.

### Existing approaches

The UN, more precisely UNECE, has recently published a version of their Buy Ship Pay -vocabulary for global trade purposes in a JSON-LD format > https://vocabulary.uncefact.org/

The vocabulary is accessible and reusable online from the Finnish National Interoperability Platform (see Google translated description in English: https://www-suomidigi-fi.translate.goog/ohjeet-ja-tuki/yhteentoimivuusalusta?_x_tr_sl=fi&_x_tr_tl=en&_x_tr_hl=fi&_x_tr_pto=wapp) due to the use of resolvable URIs and content negotiation on server:

"Content Negotiation
Machine readable JSON-LD term definitions are accessible using HTTP content negotiation:
curl https://vocabulary.uncefact.org/ -H 'Accept: application/ld+json'
curl https://vocabulary.uncefact.org/unlocode# -H 'Accept: application/ld+json'

### Links

https://vocabulary.uncefact.org/
https://tietomallit.suomi.fi/

### Requirements

Publication of the EU Core Vocabularies (at least Person and Business) as W3C Linked Data, using resolvable URIs and content negotiation on the server in a similar manner as the UN/CEFACT has done regarding the Buy Ship Pay JSON-LD Vocabulary.

### Related use cases

Related use cases

### Comments

This issue is identical with the issue 
https://github.com/SEMICeu/Core-Person-Vocabulary/issues/43

Issue was duplicated since it concerns both core vocabularies (and others as well) in a similar manner.

**Comment by EmielPwC** [comment]
The URI are currently not expressed in JSON-LD but they are dereferenceable in other RDF formats. The resolution of this issue continues on [this issue](https://github.com/SEMICeu/Core-Location-Vocabulary/issues/28).
