### ISSUE TITLE
Merging CPV, CPOV, CBV into one single CAGV

### ISSUE THREAD

**Issue by paulakeen** [SEMICeu/Core-Business-Vocabulary#6]
Please see CPV [Issue #6](https://github.com/SEMICeu/Core-Person-Vocabulary/issues/6)

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021, it was agreed to have a consolidated diagram:
https://github.com/SEMICeu/Core-Business-Vocabulary/tree/master/releases/2.00
