### ISSUE TITLE
Licence class

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Business-Vocabulary#7]
This issue can serve as the discussion forum to understand the need and use cases for the Licence class and to further develop it. As taken from the [Core Vocabulary specification](https://joinup.ec.europa.eu/sites/default/files/distribution/2013-10/Core_Vocabularies-Business_Location_Person-Specification-v1.00_0.pdf):

_In the context of a business register, the term licence refers to a permit to carry out a particular activity such as banking or mining. The Licence class is therefore envisaged as being similar to the Identifier Class in which a specific body is registered with a recognised authority. As with the Change class, the working group hopes that near future work can be done to ensure that such a class is well defined._

_Two inverse relationships are entailed by the Licence Class: {holdsLicence Licence} and {heldBy Legal Entity}._

What should be included under this class? General rights/permits to provide or carry specific activities? Rights provided to an organisation through a patent?

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-04-23, it was agreed to remove the class from the Core Vocabulary, because (1) it does not belong to a Core Vocabulary, (2) it may differ from one sector to another and (3) most businesses do not hold a single licence.

**Comment by EmidioStani** [comment]
Resolved
