### ISSUE TITLE
General comment: different level of granularity of  Core Business wrt CPOV

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Business-Vocabulary#8]
This is a general comment.
A Business is once again an organisation. What changes is the legalForm type and the way probably in which it is identified  and classified because in one case there the public law that applies and in the other the private law.

However, the two Core vocs have a different granularity of modelling.  In this Core Business Vocabulary, there is no indication of possible change events that may happen for businesses too, there is a different way to model the address (here there is registeredAddress property but in CPOV there is address),  there is no mention of contact points, there is no idea of the structure of the business in terms of departments.

This makes me think also to:
1) the name used here, i.e., "LegalEntity". Also a PublicOrganisation is a LegalEntity in the general sense, because it is established according to some (public) law. BTW,. there is an attempt to clarify this in the definition of LegalEntity. Therefore, I am not so sure if LegalEntity is a good term. In the epo ontology we tried to model Organisation and then specialize it in PublicOrganisation and Business (this latter term is also used in the SDG model), where business represents a private organisation registered in a business registry.  With the general Organisation concept you also may capture all those cases that fall under the definition "Many organisations exist that are not Legal Entities" that you report.
2) CPOV and Core Business share potentially many things because in both cases we are speaking about Organisation (as it is in Org ontology indeed).

Owing to these two comments, probably a discussion about the role of these two vocs can be further done.

**Comment by aidig** [comment]
Furthermore, this issue might be relevant here too https://github.com/SEMICeu/CPOV/issues/14.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021, it was agreed to evaluate the granularity case by case, when needed, overall the idea is to have the whole picture with the consolidated diagram and take decision when needed:
https://github.com/SEMICeu/Core-Business-Vocabulary/tree/master/releases/2.00
