### ISSUE TITLE
FormalOrganization description

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Business-Vocabulary#9]
In the description I would say that FormalOrganization is a class defined in Org, as depicted in the diagram.

**Comment by dimi-schepers** [comment]
No objection was made to this proposition during the Core Vocs webinar dd. 2021-04-23.

**Comment by EmidioStani** [comment]
With the new HTML specification, the UML class diagram highlight that FormalOrganization is specificied in Org ontology, in addition the URI linked at the class point to it: https://semiceu.github.io/Core-Business-Vocabulary/releases/2.00/#Formal%20Organization
